# data types

In [ ]:
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# S - string


In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
# print(type(a))
print(a.dtype)

int64


In [3]:
a = np.array(["ab","ju8"])

print(a.dtype)



#U: Represents a Unicode string data type in NumPy.
#3: Indicates the maximum length of each string in the array, in terms of Unicode characters.

<U3


In [4]:
a = np.array([2.7,9.0])

print(a.dtype)

float64


In [5]:
a = np.array([1+3j])

print(a.dtype)

complex128


In [6]:
c=np.array([1,2,3,4],dtype='S')
print(c)
print(c.dtype)
# type
#byte strings

[b'1' b'2' b'3' b'4']
|S1


In [11]:
# i8 mention size
a = np.array([1, 2, 3, 4], dtype='i8')

print(a)
print(a.dtype)

[1 2 3 4]
int64


In [12]:
#connot change integer

a = np.array(['a', '2', '3'], dtype='i2')
a

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
a = np.array(['a', 'juookk882', '33893'], dtype='S')
print(a)
print(a.dtype)

In [ ]:
a = np.array(['1', '2', '3'], dtype='i8')
print(a)
print(a.dtype)

In [ ]:
b=a.astype("S")
b

In [ ]:
newa = np.array([1.1, 2.1, 3.1])

newarr = newa.astype(int)

print(newarr)
print(newarr.dtype)

In [ ]:
newa = np.array(["1", "2", "3"])

newarr = newa.astype("i8")

print(newarr)
print(newarr.dtype)

In [ ]:
newa = np.array([1, 0, 3])

newarr = newa.astype(bool)

print(newarr)

print(newarr.dtype)

# Copy and view

In [13]:
import numpy as np

a = np.array([1, 2, 3, 4, 5,8,10])



x = a.copy()
x[0] = 42

print(a)
print(x)

[ 1  2  3  4  5  8 10]
[42  2  3  4  5  8 10]


In [14]:
a = np.array([1, 2, 3, 4, 5])
x = a.view()
x[0] = 42

print(a)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [19]:

import numpy as np

# Arrays
a = np.array([[1, 2, 3],[1, 2, 3]])
b = np.array([[4, 5, 6],[1, 2, 3]])

# Operations
addition = a + b         # [5, 7, 9]
subtraction = a - b      # [-3, -3, -3]
multiplication = a * b   # [4, 10, 18]
division = a / b         # [0.25, 0.4, 0.5]

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)


Addition: [[5 7 9]
 [2 4 6]]
Subtraction: [[-3 -3 -3]
 [ 0  0  0]]
Multiplication: [[ 4 10 18]
 [ 1  4  9]]
Division: [[0.25 0.4  0.5 ]
 [1.   1.   1.  ]]
