In [ ]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
list3 = list1 + list2
print(list3)

In [ ]:
import numpy as np
a=np.array([[2,3,4,5],[4,5,7,8]])
b=np.array([[9,9,6,5],[3,5,1,8]])
addition=a+b
sub=a-b
multi=a*b
div=a/b

print("addition",addition)
print("sub",sub)
print("multi",multi)
print("div",div)

In [ ]:
import numpy as arr
a=arr.array([1,2,3,4,5,6,7,8,9,0])
serma=a.reshape(5,2)
print(serma)

In [13]:
import numpy as arr
a=arr.array([1,2,3,4,5,6,7,8,9,0,11,12])
serma=a.reshape(3,2,2)
print(serma)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9  0]
  [11 12]]]
